version: "3.9"
services:
  terraform:
    build: 
      context: .
      dockerfile: terraform.Dockerfile
    volumes:
      - .:/work
    working_dir: /work
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    command: ["sh", "-c", "terraform init && terraform apply -auto-approve"]

  birmingham-biz:
    build:
      context: .
    ports:
      - "8080:80"

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
